import Dunkest_BOT
from utils import printing_helper, maximization_helper, IO_read_write_helper

bot = Dunkest_BOT.dunkest_bot()
print("Reading all the data")
IO_read_write_helper.read_data_from_disk(bot)
print("All the data analyzed")
print("--------------------------------------")
print("Now you can select some stuffs")
#bot.keep_players_choice()
#bot.remove_players_choice()
bot.select_coach_choice()
#bot.select_coach()
print("Choice completed")
print("--------------------------------------")
print("Starting to compute the best mix of players for maximizing the total score")
maximization_helper.maximization_scores(bot, False, True)
print("Computation done, now the final print")
print("--------------------------------------")
result = printing_helper.final_print(bot)
text_file = open("data/output_final_order_by_fantasy_pts.txt", "w")
text_file.write(result)
text_file.close()
print("Computation done, data written to disk")
